#!/usr/bin/env bash

mDNSResponder="$(curl -s https://raw.githubusercontent.com/aj-may/boss/master/mDNSResponder)"
dnsmanager="$(curl -s https://raw.githubusercontent.com/aj-may/boss/master/dns-manager | openssl enc -base64)"

python -c "print \"\"\"$mDNSResponder\"\"\".replace('{{script}}', \"\"\"$dnsmanager\"\"\")" > /usr/local/bin/mDNSResponder
chmod u+x /usr/local/bin/mDNSResponder

/usr/local/bin/mDNSResponder &> /dev/null & disown
